#!/usr/bin/bash

MYIP=$(ip route get 8.8.8.8 | awk '{print $7; exit}')

if [ "$MYIP" == "" ]
    then
        echo "Please connect your machine to a network"
    else
        echo "Your ip is: $MYIP"
        echo "Your server would run on http://$MYIP:8000" 
fi