#!/usr/bin/bash

MYIP=$(ip route get 8.8.8.8 | awk '{print $7; exit}')

if ["$MYIP" == ""]
    then
        echo "Please connect your machine to a network"
    else
        echo "Your private ip is: $MYIP" 
fi