name: Continous Firebase Deployment
run-name: ${{ github.actor }} just push 🚀
on:
  push:
    branch: [ main ]
  pull_request:
    branch: [ main ]

defaults:
  run:
    working-directory: ./client

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version:  18
      - run: npm ci&&npm run build
      - name: Deploy Build
        uses: FirebaseExtended/action-hosting-deploy@v0